ignore:
  - test/**/*
coverage:
  range: 70..90
  round: down
  precision: 2
  status:
    project:
      default: false
      tests:
        target: 100%
        paths: "tests/"
      app:
        paths: "!tests/"
