version: '3'

services:
  app:
    build: ./app
    container_name: 'admv-app'
    command: npm run dev
    ports:
      - '8000:80'
    volumes:
      - ./app:/app
  api:
    build: ./api
    container_name: 'admv-api'
    command: npm run dev
    ports:
      - '5000:5000'
    links:
      - database
    volumes:
      - ./api:/api
  database:
    build: ./database
    container_name: 'admv-database'
    ports:
      - '33060:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./database/dump:/dump
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'admv-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
